baseURL = "/"
languageCode = "en-us"
title = "Technology Blog Wim"
theme = "mainroad"
pygmentsCodefences = true
pygmentsStyle = "pygments"
summaryLength = 20
paginate = 10
googleAnalytics="UA-83351442-2"
disqusShortname = "blog-wimwauters"

[Author] # Used in authorbox
  name = "Wim"
  avatar = "img/avatar.png"

[menu] 
  [[menu.main]]
  identifier = "Network Programmability"
  name = "Network Programmability"
  url = "/network-programming"
  weight = 1

  [[menu.main]]
  identifier = "DevOps"
  name = "DevOps"
  url = "/devops"
  weight = 2

  [[menu.main]]
  identifier = "Web Development"
  name = "Web Development"
  url = "/web-development"
  weight = 3

  [[menu.main]]
  identifier = "cloud"
  name = "Cloud"
  url = "/categories/public-cloud"
  weight = 4

  [[menu.main]]
  identifier = "cloud-native"
  name = "Cloud-Native"
  url = "/categories/cloud-native/"
  weight = 5

[[menu.main]]
  identifier = "about"
  name = "About Me"
  url = "/about"
  weight = 6



[Params]
  subtitle = "Blog Wim Wauters" # Subtitle of your site. Used in site header
  copyright = "Wim Wauters" # Footer copyright holder, otherwise will use site title
  logo = "img/logo_blog.png"
  readmore = true
  highlightColor = "#9f0101" # Override highlight color
  customCSS = ["css/custom.css"] # Include custom CSS files
  post_navigation = true # Show post navigation at bottom of pages if true
  post_meta = ["date"] # Order of post meta information
  canonifyURLs = true

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "right"  # Configure layout for list pages
  single = "right" # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["categories", "taglist", "social"]

[Params.widgets.social]
  # Enable parts of social widget
  twitter = "@Wauters_Wim"
  linkedin = "https://www.linkedin.com/in/wim-wauters-92ab401"
  github = "https://github.com/wiwa1978"
  email = "blogwimwauters at gmail.com"